import { LevelConfig } from '../types/game';

export const LEVEL_REGISTRY: Record<number, LevelConfig> = {
  1: {
    level: 1,
    name: 'Novice',
    depth: 1,
    blunderRate: 0.75,
    aggressionWeight: 0.3,
    positionWeight: 5,
    safetyWeight: 0.1,
  },
  2: {
    level: 2,
    name: 'Apprentice',
    depth: 1,
    blunderRate: 0.55,
    aggressionWeight: 0.4,
    positionWeight: 6,
    safetyWeight: 0.2,
  },
  3: {
    level: 3,
    name: 'Casual',
    depth: 2,
    blunderRate: 0.40,
    aggressionWeight: 0.5,
    positionWeight: 7,
    safetyWeight: 0.3,
  },
  4: {
    level: 4,
    name: 'Competent',
    depth: 2,
    blunderRate: 0.30,
    aggressionWeight: 0.6,
    positionWeight: 8,
    safetyWeight: 0.4,
  },
  5: {
    level: 5,
    name: 'Strategist',
    depth: 3,
    blunderRate: 0.20,
    aggressionWeight: 0.8,
    positionWeight: 10,
    safetyWeight: 0.5,
  },
  6: {
    level: 6,
    name: 'Tactician',
    depth: 3,
    blunderRate: 0.12,
    aggressionWeight: 0.9,
    positionWeight: 12,
    safetyWeight: 0.6,
  },
  7: {
    level: 7,
    name: 'Commander',
    depth: 4,
    blunderRate: 0.08,
    aggressionWeight: 1.0,
    positionWeight: 15,
    safetyWeight: 0.7,
  },
  8: {
    level: 8,
    name: 'Expert',
    depth: 4,
    blunderRate: 0.04,
    aggressionWeight: 1.1,
    positionWeight: 18,
    safetyWeight: 0.8,
  },
  9: {
    level: 9,
    name: 'Champion',
    depth: 5,
    blunderRate: 0.02,
    aggressionWeight: 1.2,
    positionWeight: 22,
    safetyWeight: 0.9,
  },
  10: {
    level: 10,
    name: 'Grandmaster',
    depth: 5,
    blunderRate: 0.00,
    aggressionWeight: 1.3,
    positionWeight: 25,
    safetyWeight: 1.0,
  },
};
